### ISSUE TITLE
Document new/better way to add filters to the storefront

### ISSUE THREAD

**Issue by svlauer** [shopware/docs#458]
[The current plugin guide portion on adding filters to the storefront](https://developer.shopware.com/docs/guides/plugins/plugins/storefront/add-listing-filters#add-your-filter-to-the-storefront-ui) recommends to overwrite-with-`parent()` the last filter provided by core (which happens to be, as of this writing, the "shipping-free" filter).

After [platform pull request #2247](https://github.com/shopware/platform/pull/2247)  (which has been merged, but is not yet part of a release), this should be replaced with a recommendation to overwrite-with-`parent()` the new block `block component_filter_panel_items`, which is a more robust solution.

I am happy to roll a pull request for this doc change, but I am uncertain as to whether it is appropriate to do it right away - regardless of when the change will be released, the doc change should go only in the docs for the next major release 6.5 (because there are several 6.4 versions that do not contain the new block).

**Comment by tobiasberge** [comment]
Hi @svlauer,

thank you for your contribution.

In general I would agree to document the new `component_filter_panel_items` because it is very unlikely to change compared to specific filters. However there may be cases where the developer want's to have a new filter before or after another filter. Maybe we could document the `component_filter_panel_items` as the primary solution and then add another sentence like "If you need your filter next to a specific filter, you can also use the filter's individual blocks e.g. `component_filter_panel_item_shipping_free` {code_exmample}".

For the version: I think you could prepare an info box in your pull request which stays open until it is clear in which version the block will be released. Approximately this could be `v6.4.8.0`:

```
{% hint style="info" %}
The block `component_filter_panel_items` is available from Shopware Version 6.4.8.0
{% endhint %}
```

**Comment by svlauer** [comment]
This sounds sensible. Given the (suboptimal) hardcoding of the order of the filters provided by core, it is good to have the additional hint, as you suggest.

Thank you for you tip with the info box! I plan to roll a pull request soonish.

**Comment by svlauer** [comment]
Quick question (not sure if this is the best place to ask - feel free to tell me to go somewhere else):

Is there a way for me to "build" the documentation locally, to test my changes before doing a pull request? I can of course test the basic markdown easily, but what about `{% code %}` or `{% hint %}` directives? (I am not familiar with gitbook, and looking at their website is not terribly helpful ...)

**Comment by elkmod** [comment]
Hi @svlauer. Thank you a lot for the pull request! As of now, unfortunately, we're unaware of a proper way to preview the changes. I propose that we will review the published article, once the PR has been merged and, if necessary, make some quick fixes.

**Comment by svlauer** [comment]
Thanks for the explanation! Ok ... the template tags are simple enough, so probably everything is going to be fine. But it felt wrong to do a PR without proper testing ... (and I thought I must have missed something).
