### ISSUE TITLE
Increment Storage / Number Ranges Documentation is missing dependency on shopware.cart.redis

### ISSUE THREAD

**Issue by jr-timme** [shopware/docs#571]
When configuring the increment storage and number ranges to use redis as described in the documentation the shopware console generates the following error:
```
The service "Shopware\Core\System\NumberRange\ValueGenerator\Pattern\IncrementStorage\IncrementRedisStorage" has a dependency on a non-existent service "shopware.cart.redis"
```

I think the documentation should be expanded to also include that it is necessary to configure `shopware.cart.redis_url` as well.

It's possible that this is only a dependency for either the number_ranges or the increment storage.
I configured both simultaneously and the error message contains both parts in the mentioned path.
I did not investigate this further as everything seems to work after adding `shopware.cart.redis_url` as well.

https://github.com/shopware/docs/blob/master/guides/hosting/performance/number-ranges.md
https://github.com/shopware/docs/blob/master/guides/hosting/performance/increment.md

**Comment by keulinho** [comment]
Thanks for bringing up this issue and sorry that it took us so long to respond :v: 

It was not just an docs issue, but in fact a bug in how the `number_ranges` services where created, that was resolved in the meantime: https://github.com/shopware/platform/pull/2756

So with current shopware version you shouldn't need to define a `shopware.cart.redis` in order to use the redis implementation for the number ranges.
